package utils;

public enum Icon {
    _360("360.png"), _3D_ROTATION("3d_rotation.png"), _4K("4k.png"), AC_UNIT("ac_unit.png"),
    ACCESS_ALARM("access_alarm.png"), ACCESS_ALARMS("access_alarms.png"), ACCESS_TIME("access_time.png"),
    ACCESSIBILITY("accessibility.png"), ACCESSIBILITY_NEW("accessibility_new.png"), ACCESSIBLE("accessible.png"),
    ACCESSIBLE_FORWARD("accessible_forward.png"), ACCOUNT_BALANCE("account_balance.png"),
    ACCOUNT_BALANCE_WALLET("account_balance_wallet.png"), ACCOUNT_BOX("account_box.png"),
    ACCOUNT_CIRCLE("account_circle.png"), ACCOUNT_TREE("account_tree.png"), ADB("adb.png"), ADD("add.png"),
    ADD_A_PHOTO("add_a_photo.png"), ADD_ALARM("add_alarm.png"), ADD_ALERT("add_alert.png"), ADD_BOX("add_box.png"),
    ADD_CIRCLE("add_circle.png"), ADD_CIRCLE_OUTLINE("add_circle_outline.png"), ADD_COMMENT("add_comment.png"),
    ADD_LOCATION("add_location.png"), ADD_PHOTO_ALTERNATE("add_photo_alternate.png"),
    ADD_SHOPPING_CART("add_shopping_cart.png"), ADD_TO_HOME_SCREEN("add_to_home_screen.png"),
    ADD_TO_PHOTOS("add_to_photos.png"), ADD_TO_QUEUE("add_to_queue.png"), ADJUST("adjust.png"),
    AIRLINE_SEAT_FLAT("airline_seat_flat.png"), AIRLINE_SEAT_FLAT_ANGLED("airline_seat_flat_angled.png"),
    AIRLINE_SEAT_INDIVIDUAL_SUITE("airline_seat_individual_suite.png"),
    AIRLINE_SEAT_LEGROOM_EXTRA("airline_seat_legroom_extra.png"),
    AIRLINE_SEAT_LEGROOM_NORMAL("airline_seat_legroom_normal.png"),
    AIRLINE_SEAT_LEGROOM_REDUCED("airline_seat_legroom_reduced.png"),
    AIRLINE_SEAT_RECLINE_EXTRA("airline_seat_recline_extra.png"),
    AIRLINE_SEAT_RECLINE_NORMAL("airline_seat_recline_normal.png"), AIRPLANEMODE_ACTIVE("airplanemode_active.png"),
    AIRPLANEMODE_INACTIVE("airplanemode_inactive.png"), AIRPLAY("airplay.png"), AIRPORT_SHUTTLE("airport_shuttle.png"),
    ALARM("alarm.png"), ALARM_ADD("alarm_add.png"), ALARM_OFF("alarm_off.png"), ALARM_ON("alarm_on.png"),
    ALBUM("album.png"), ALL_INBOX("all_inbox.png"), ALL_INCLUSIVE("all_inclusive.png"), ALL_OUT("all_out.png"),
    ALTERNATE_EMAIL("alternate_email.png"), AMP_STORIES("amp_stories.png"), ANDROID("android.png"),
    ANNOUNCEMENT("announcement.png"), APARTMENT("apartment.png"), APPS("apps.png"), ARCHIVE("archive.png"),
    ARROW_BACK("arrow_back.png"), ARROW_BACK_IOS("arrow_back_ios.png"), ARROW_DOWNWARD("arrow_downward.png"),
    ARROW_DROP_DOWN("arrow_drop_down.png"), ARROW_DROP_DOWN_CIRCLE("arrow_drop_down_circle.png"),
    ARROW_DROP_UP("arrow_drop_up.png"), ARROW_FORWARD("arrow_forward.png"), ARROW_FORWARD_IOS("arrow_forward_ios.png"),
    ARROW_LEFT("arrow_left.png"), ARROW_RIGHT("arrow_right.png"), ARROW_RIGHT_ALT("arrow_right_alt.png"),
    ARROW_UPWARD("arrow_upward.png"), ART_TRACK("art_track.png"), ASPECT_RATIO("aspect_ratio.png"),
    ASSESSMENT("assessment.png"), ASSIGNMENT("assignment.png"), ASSIGNMENT_IND("assignment_ind.png"),
    ASSIGNMENT_LATE("assignment_late.png"), ASSIGNMENT_RETURN("assignment_return.png"),
    ASSIGNMENT_RETURNED("assignment_returned.png"), ASSIGNMENT_TURNED_IN("assignment_turned_in.png"),
    ASSISTANT("assistant.png"), ASSISTANT_PHOTO("assistant_photo.png"), ATM("atm.png"), ATTACH_FILE("attach_file.png"),
    ATTACH_MONEY("attach_money.png"), ATTACHMENT("attachment.png"), AUDIOTRACK("audiotrack.png"),
    AUTORENEW("autorenew.png"), AV_TIMER("av_timer.png"), BACKSPACE("backspace.png"), BACKUP("backup.png"),
    BALLOT("ballot.png"), BAR_CHART("bar_chart.png"), BARCODE("barcode.png"), BATHTUB("bathtub.png"),
    BATTERY_20("battery_20.png"), BATTERY_30("battery_30.png"), BATTERY_50("battery_50.png"),
    BATTERY_60("battery_60.png"), BATTERY_80("battery_80.png"), BATTERY_90("battery_90.png"),
    BATTERY_ALERT("battery_alert.png"), BATTERY_CHARGING_20("battery_charging_20.png"),
    BATTERY_CHARGING_30("battery_charging_30.png"), BATTERY_CHARGING_50("battery_charging_50.png"),
    BATTERY_CHARGING_60("battery_charging_60.png"), BATTERY_CHARGING_80("battery_charging_80.png"),
    BATTERY_CHARGING_90("battery_charging_90.png"), BATTERY_CHARGING_FULL("battery_charging_full.png"),
    BATTERY_FULL("battery_full.png"), BATTERY_STD("battery_std.png"), BATTERY_UNKNOWN("battery_unknown.png"),
    BEACH_ACCESS("beach_access.png"), BEENHERE("beenhere.png"), BLOCK("block.png"), BLUETOOTH("bluetooth.png"),
    BLUETOOTH_AUDIO("bluetooth_audio.png"), BLUETOOTH_CONNECTED("bluetooth_connected.png"),
    BLUETOOTH_DISABLED("bluetooth_disabled.png"), BLUETOOTH_SEARCHING("bluetooth_searching.png"),
    BLUR_CIRCULAR("blur_circular.png"), BLUR_LINEAR("blur_linear.png"), BLUR_OFF("blur_off.png"),
    BLUR_ON("blur_on.png"), BOOK("book.png"), BOOKMARK("bookmark.png"), BOOKMARK_BORDER("bookmark_border.png"),
    BOOKMARKS("bookmarks.png"), BORDER_ALL("border_all.png"), BORDER_BOTTOM("border_bottom.png"),
    BORDER_CLEAR("border_clear.png"), BORDER_COLOR("border_color.png"), BORDER_HORIZONTAL("border_horizontal.png"),
    BORDER_INNER("border_inner.png"), BORDER_LEFT("border_left.png"), BORDER_OUTER("border_outer.png"),
    BORDER_RIGHT("border_right.png"), BORDER_STYLE("border_style.png"), BORDER_TOP("border_top.png"),
    BORDER_VERTICAL("border_vertical.png"), BRANDING_WATERMARK("branding_watermark.png"),
    BRIGHTNESS_1("brightness_1.png"), BRIGHTNESS_2("brightness_2.png"), BRIGHTNESS_3("brightness_3.png"),
    BRIGHTNESS_4("brightness_4.png"), BRIGHTNESS_5("brightness_5.png"), BRIGHTNESS_6("brightness_6.png"),
    BRIGHTNESS_7("brightness_7.png"), BRIGHTNESS_AUTO("brightness_auto.png"), BRIGHTNESS_HIGH("brightness_high.png"),
    BRIGHTNESS_LOW("brightness_low.png"), BRIGHTNESS_MEDIUM("brightness_medium.png"), BROKEN_IMAGE("broken_image.png"),
    BRUSH("brush.png"), BUBBLE_CHART("bubble_chart.png"), BUG_REPORT("bug_report.png"), BUILD("build.png"),
    BURST_MODE("burst_mode.png"), BUSINESS("business.png"), BUSINESS_CENTER("business_center.png"),
    CACHED("cached.png"), CAKE("cake.png"), CALENDAR_TODAY("calendar_today.png"),
    CALENDAR_VIEW_DAY("calendar_view_day.png"), CALL("call.png"), CALL_END("call_end.png"), CALL_MADE("call_made.png"),
    CALL_MERGE("call_merge.png"), CALL_MISSED("call_missed.png"), CALL_MISSED_OUTGOING("call_missed_outgoing.png"),
    CALL_RECEIVED("call_received.png"), CALL_SPLIT("call_split.png"), CALL_TO_ACTION("call_to_action.png"),
    CAMERA("camera.png"), CAMERA_ALT("camera_alt.png"), CAMERA_ENHANCE("camera_enhance.png"),
    CAMERA_FRONT("camera_front.png"), CAMERA_REAR("camera_rear.png"), CAMERA_ROLL("camera_roll.png"),
    CANCEL("cancel.png"), CANCEL_PRESENTATION("cancel_presentation.png"),
    CANCEL_SCHEDULE_SEND("cancel_schedule_send.png"), CARD_GIFTCARD("card_giftcard.png"),
    CARD_MEMBERSHIP("card_membership.png"), CARD_TRAVEL("card_travel.png"), CASINO("casino.png"), CAST("cast.png"),
    CAST_CONNECTED("cast_connected.png"), CAST_FOR_EDUCATION("cast_for_education.png"), CATEGORY("category.png"),
    CELL_WIFI("cell_wifi.png"), CENTER_FOCUS_STRONG("center_focus_strong.png"),
    CENTER_FOCUS_WEAK("center_focus_weak.png"), CHANGE_HISTORY("change_history.png"), CHAT("chat.png"),
    CHAT_BUBBLE("chat_bubble.png"), CHAT_BUBBLE_OUTLINE("chat_bubble_outline.png"), CHECK("check.png"),
    CHECK_BOX("check_box.png"), CHECK_BOX_OUTLINE_BLANK("check_box_outline_blank.png"),
    CHECK_CIRCLE("check_circle.png"), CHECK_CIRCLE_OUTLINE("check_circle_outline.png"),
    CHEVRON_LEFT("chevron_left.png"), CHEVRON_RIGHT("chevron_right.png"), CHILD_CARE("child_care.png"),
    CHILD_FRIENDLY("child_friendly.png"), CHROME_READER_MODE("chrome_reader_mode.png"), CLASS("class.png"),
    CLEAR("clear.png"), CLEAR_ALL("clear_all.png"), CLOSE("close.png"), CLOSED_CAPTION("closed_caption.png"),
    CLOUD("cloud.png"), CLOUD_CIRCLE("cloud_circle.png"), CLOUD_DONE("cloud_done.png"),
    CLOUD_DOWNLOAD("cloud_download.png"), CLOUD_OFF("cloud_off.png"), CLOUD_QUEUE("cloud_queue.png"),
    CLOUD_UPLOAD("cloud_upload.png"), CODE("code.png"), COLLECTIONS("collections.png"),
    COLLECTIONS_BOOKMARK("collections_bookmark.png"), COLOR_LENS("color_lens.png"), COLORIZE("colorize.png"),
    COMMENT("comment.png"), COMMUTE("commute.png"), COMPARE("compare.png"), COMPARE_ARROWS("compare_arrows.png"),
    COMPASS_CALIBRATION("compass_calibration.png"), COMPUTER("computer.png"),
    CONFIRMATION_NUMBER("confirmation_number.png"), CONTACT_MAIL("contact_mail.png"),
    CONTACT_PHONE("contact_phone.png"), CONTACT_SUPPORT("contact_support.png"), CONTACTLESS("contactless.png"),
    CONTACTS("contacts.png"), CONTENT_COPY("content_copy.png"), CONTENT_CUT("content_cut.png"),
    CONTENT_PASTE("content_paste.png"), CONTROL_CAMERA("control_camera.png"), CONTROL_POINT("control_point.png"),
    CONTROL_POINT_DUPLICATE("control_point_duplicate.png"), COPYRIGHT("copyright.png"), CREATE("create.png"),
    CREATE_NEW_FOLDER("create_new_folder.png"), CREDIT_CARD("credit_card.png"), CROP("crop.png"),
    CROP_16_9("crop_16_9.png"), CROP_3_2("crop_3_2.png"), CROP_5_4("crop_5_4.png"), CROP_7_5("crop_7_5.png"),
    CROP_DIN("crop_din.png"), CROP_FREE("crop_free.png"), CROP_LANDSCAPE("crop_landscape.png"),
    CROP_ORIGINAL("crop_original.png"), CROP_PORTRAIT("crop_portrait.png"), CROP_ROTATE("crop_rotate.png"),
    CROP_SQUARE("crop_square.png"), DASHBOARD("dashboard.png"), DATA_USAGE("data_usage.png"),
    DATE_RANGE("date_range.png"), DECK("deck.png"), DEHAZE("dehaze.png"), DELETE("delete.png"),
    DELETE_FOREVER("delete_forever.png"), DELETE_OUTLINE("delete_outline.png"), DELETE_SWEEP("delete_sweep.png"),
    DEPARTURE_BOARD("departure_board.png"), DESCRIPTION("description.png"),
    DESKTOP_ACCESS_DISABLED("desktop_access_disabled.png"), DESKTOP_MAC("desktop_mac.png"),
    DESKTOP_WINDOWS("desktop_windows.png"), DETAILS("details.png"), DEVELOPER_BOARD("developer_board.png"),
    DEVELOPER_MODE("developer_mode.png"), DEVICE_HUB("device_hub.png"), DEVICE_UNKNOWN("device_unknown.png"),
    DEVICES("devices.png"), DEVICES_OTHER("devices_other.png"), DIALER_SIP("dialer_sip.png"), DIALPAD("dialpad.png"),
    DIRECTIONS("directions.png"), DIRECTIONS_BIKE("directions_bike.png"), DIRECTIONS_BOAT("directions_boat.png"),
    DIRECTIONS_BUS("directions_bus.png"), DIRECTIONS_CAR("directions_car.png"),
    DIRECTIONS_RAILWAY("directions_railway.png"), DIRECTIONS_RUN("directions_run.png"),
    DIRECTIONS_SUBWAY("directions_subway.png"), DIRECTIONS_TRANSIT("directions_transit.png"),
    DIRECTIONS_WALK("directions_walk.png"), DISC_FULL("disc_full.png"), DIVIDE("divide.png"), DNS("dns.png"),
    DO_NOT_DISTURB("do_not_disturb.png"), DO_NOT_DISTURB_ALT("do_not_disturb_alt.png"),
    DO_NOT_DISTURB_OFF("do_not_disturb_off.png"), DOCK("dock.png"), DOMAIN("domain.png"),
    DOMAIN_DISABLED("domain_disabled.png"), DONE("done.png"), DONE_ALL("done_all.png"),
    DONE_OUTLINE("done_outline.png"), DONUT_LARGE("donut_large.png"), DONUT_SMALL("donut_small.png"),
    DOUBLE_ARROW("double_arrow.png"), DRAFTS("drafts.png"), DRAG_HANDLE("drag_handle.png"),
    DRAG_INDICATOR("drag_indicator.png"), DRIVE_ETA("drive_eta.png"), DUO("duo.png"), DVR("dvr.png"),
    DYNAMIC_FEED("dynamic_feed.png"), ECO("eco.png"), EDIT("edit.png"), EDIT_ATTRIBUTES("edit_attributes.png"),
    EDIT_LOCATION("edit_location.png"), EJECT("eject.png"), EMAIL("email.png"), EMOJI_EMOTIONS("emoji_emotions.png"),
    EMOJI_EVENTS("emoji_events.png"), EMOJI_FLAGS("emoji_flags.png"), EMOJI_FOOD_BEVERAGE("emoji_food_beverage.png"),
    EMOJI_NATURE("emoji_nature.png"), EMOJI_OBJECTS("emoji_objects.png"), EMOJI_PEOPLE("emoji_people.png"),
    EMOJI_SYMBOLS("emoji_symbols.png"), EMOJI_TRANSPORTATION("emoji_transportation.png"),
    ENHANCED_ENCRYPTION("enhanced_encryption.png"), EQUALIZER("equalizer.png"), EQUALS("equals.png"),
    ERROR("error.png"), ERROR_OUTLINE("error_outline.png"), EURO("euro.png"), EURO_SYMBOL("euro_symbol.png"),
    EV_STATION("ev_station.png"), EVENT("event.png"), EVENT_AVAILABLE("event_available.png"),
    EVENT_BUSY("event_busy.png"), EVENT_NOTE("event_note.png"), EVENT_SEAT("event_seat.png"),
    EXIT_TO_APP("exit_to_app.png"), EXPAND_LESS("expand_less.png"), EXPAND_MORE("expand_more.png"),
    EXPLICIT("explicit.png"), EXPLORE("explore.png"), EXPLORE_OFF("explore_off.png"), EXPOSURE("exposure.png"),
    EXPOSURE_NEG_1("exposure_neg_1.png"), EXPOSURE_NEG_2("exposure_neg_2.png"), EXPOSURE_PLUS_1("exposure_plus_1.png"),
    EXPOSURE_PLUS_2("exposure_plus_2.png"), EXPOSURE_ZERO("exposure_zero.png"), EXTENSION("extension.png"),
    FACE("face.png"), FAST_FORWARD("fast_forward.png"), FAST_REWIND("fast_rewind.png"), FASTFOOD("fastfood.png"),
    FAVORITE("favorite.png"), FAVORITE_BORDER("favorite_border.png"), FEATURED_PLAY_LIST("featured_play_list.png"),
    FEATURED_VIDEO("featured_video.png"), FEEDBACK("feedback.png"), FIBER_DVR("fiber_dvr.png"),
    FIBER_MANUAL_RECORD("fiber_manual_record.png"), FIBER_NEW("fiber_new.png"), FIBER_PIN("fiber_pin.png"),
    FIBER_SMART_RECORD("fiber_smart_record.png"), FILE_COPY("file_copy.png"), FILE_UPLOAD("file_upload.png"),
    FILTER("filter.png"), FILTER_1("filter_1.png"), FILTER_2("filter_2.png"), FILTER_3("filter_3.png"),
    FILTER_4("filter_4.png"), FILTER_5("filter_5.png"), FILTER_6("filter_6.png"), FILTER_7("filter_7.png"),
    FILTER_8("filter_8.png"), FILTER_9("filter_9.png"), FILTER_9_PLUS("filter_9_plus.png"),
    FILTER_B_AND_W("filter_b_and_w.png"), FILTER_CENTER_FOCUS("filter_center_focus.png"),
    FILTER_DRAMA("filter_drama.png"), FILTER_FRAMES("filter_frames.png"), FILTER_HDR("filter_hdr.png"),
    FILTER_LIST("filter_list.png"), FILTER_NONE("filter_none.png"), FILTER_TILT_SHIFT("filter_tilt_shift.png"),
    FILTER_VINTAGE("filter_vintage.png"), FIND_IN_PAGE("find_in_page.png"), FIND_REPLACE("find_replace.png"),
    FINGERPRINT("fingerprint.png"), FIREPLACE("fireplace.png"), FIRST_PAGE("first_page.png"),
    FITNESS_CENTER("fitness_center.png"), FLAG("flag.png"), FLARE("flare.png"), FLASH_AUTO("flash_auto.png"),
    FLASH_OFF("flash_off.png"), FLASH_ON("flash_on.png"), FLIGHT("flight.png"), FLIGHT_LAND("flight_land.png"),
    FLIGHT_TAKEOFF("flight_takeoff.png"), FLIP("flip.png"), FLIP_CAMERA_ANDROID("flip_camera_android.png"),
    FLIP_CAMERA_IOS("flip_camera_ios.png"), FLIP_TO_BACK("flip_to_back.png"), FLIP_TO_FRONT("flip_to_front.png"),
    FOLDER("folder.png"), FOLDER_OPEN("folder_open.png"), FOLDER_SHARED("folder_shared.png"),
    FOLDER_SPECIAL("folder_special.png"), FONT_DOWNLOAD("font_download.png"),
    FORMAT_ALIGN_CENTER("format_align_center.png"), FORMAT_ALIGN_JUSTIFY("format_align_justify.png"),
    FORMAT_ALIGN_LEFT("format_align_left.png"), FORMAT_ALIGN_RIGHT("format_align_right.png"),
    FORMAT_BOLD("format_bold.png"), FORMAT_CLEAR("format_clear.png"), FORMAT_COLOR_FILL("format_color_fill.png"),
    FORMAT_COLOR_RESET("format_color_reset.png"), FORMAT_COLOR_TEXT("format_color_text.png"),
    FORMAT_INDENT_DECREASE("format_indent_decrease.png"), FORMAT_INDENT_INCREASE("format_indent_increase.png"),
    FORMAT_ITALIC("format_italic.png"), FORMAT_LINE_SPACING("format_line_spacing.png"),
    FORMAT_LIST_BULLETED("format_list_bulleted.png"), FORMAT_LIST_NUMBERED("format_list_numbered.png"),
    FORMAT_LIST_NUMBERED_RTL("format_list_numbered_rtl.png"), FORMAT_PAINT("format_paint.png"),
    FORMAT_QUOTE("format_quote.png"), FORMAT_SHAPES("format_shapes.png"), FORMAT_SIZE("format_size.png"),
    FORMAT_STRIKETHROUGH("format_strikethrough.png"), FORMAT_TEXTDIRECTION_L_TO_R("format_textdirection_l_to_r.png"),
    FORMAT_TEXTDIRECTION_R_TO_L("format_textdirection_r_to_l.png"), FORMAT_UNDERLINED("format_underlined.png"),
    FORUM("forum.png"), FORWARD("forward.png"), FORWARD_10("forward_10.png"), FORWARD_30("forward_30.png"),
    FORWARD_5("forward_5.png"), FREE_BREAKFAST("free_breakfast.png"), FULLSCREEN("fullscreen.png"),
    FULLSCREEN_EXIT("fullscreen_exit.png"), FUNCTIONS("functions.png"), G_TRANSLATE("g_translate.png"),
    GAMEPAD("gamepad.png"), GAMES("games.png"), GAVEL("gavel.png"), GESTURE("gesture.png"), GET_APP("get_app.png"),
    GIF("gif.png"), GOLF_COURSE("golf_course.png"), GPS_FIXED("gps_fixed.png"), GPS_NOT_FIXED("gps_not_fixed.png"),
    GPS_OFF("gps_off.png"), GRADE("grade.png"), GRADIENT("gradient.png"), GRAIN("grain.png"),
    GRAPHIC_EQ("graphic_eq.png"), GREATER_THAN("greater_than.png"), GREATER_THAN_EQUAL("greater_than_equal.png"),
    GRID_OFF("grid_off.png"), GRID_ON("grid_on.png"), GROUP("group.png"), GROUP_ADD("group_add.png"),
    GROUP_WORK("group_work.png"), HD("hd.png"), HDR_OFF("hdr_off.png"), HDR_ON("hdr_on.png"),
    HDR_STRONG("hdr_strong.png"), HDR_WEAK("hdr_weak.png"), HEADSET("headset.png"), HEADSET_MIC("headset_mic.png"),
    HEALING("healing.png"), HEARING("hearing.png"), HEIGHT("height.png"), HELP("help.png"),
    HELP_OUTLINE("help_outline.png"), HIGH_QUALITY("high_quality.png"), HIGHLIGHT("highlight.png"),
    HIGHLIGHT_OFF("highlight_off.png"), HISTORY("history.png"), HOME("home.png"), HOME_WORK("home_work.png"),
    HORIZONTAL_SPLIT("horizontal_split.png"), HOT_TUB("hot_tub.png"), HOTEL("hotel.png"),
    HOURGLASS_EMPTY("hourglass_empty.png"), HOURGLASS_FULL("hourglass_full.png"), HOUSE("house.png"),
    HOW_TO_REG("how_to_reg.png"), HOW_TO_VOTE("how_to_vote.png"), HTTP("http.png"), HTTPS("https.png"),
    IMAGE("image.png"), IMAGE_ASPECT_RATIO("image_aspect_ratio.png"), IMAGE_SEARCH("image_search.png"),
    IMPORT_CONTACTS("import_contacts.png"), IMPORT_EXPORT("import_export.png"),
    IMPORTANT_DEVICES("important_devices.png"), INBOX("inbox.png"),
    INDETERMINATE_CHECK_BOX("indeterminate_check_box.png"), INFO("info.png"), INPUT("input.png"),
    INSERT_CHART("insert_chart.png"), INSERT_CHART_OUTLINED("insert_chart_outlined.png"),
    INSERT_COMMENT("insert_comment.png"), INSERT_DRIVE_FILE("insert_drive_file.png"),
    INSERT_EMOTICON("insert_emoticon.png"), INSERT_INVITATION("insert_invitation.png"), INSERT_LINK("insert_link.png"),
    INSERT_PHOTO("insert_photo.png"), INVERT_COLORS("invert_colors.png"), INVERT_COLORS_OFF("invert_colors_off.png"),
    ISO("iso.png"), KEYBOARD("keyboard.png"), KEYBOARD_ARROW_DOWN("keyboard_arrow_down.png"),
    KEYBOARD_ARROW_LEFT("keyboard_arrow_left.png"), KEYBOARD_ARROW_RIGHT("keyboard_arrow_right.png"),
    KEYBOARD_ARROW_UP("keyboard_arrow_up.png"), KEYBOARD_BACKSPACE("keyboard_backspace.png"),
    KEYBOARD_CAPSLOCK("keyboard_capslock.png"), KEYBOARD_HIDE("keyboard_hide.png"),
    KEYBOARD_RETURN("keyboard_return.png"), KEYBOARD_TAB("keyboard_tab.png"), KEYBOARD_VOICE("keyboard_voice.png"),
    KING_BED("king_bed.png"), KITCHEN("kitchen.png"), LABEL("label.png"), LABEL_IMPORTANT("label_important.png"),
    LABEL_OFF("label_off.png"), LANDSCAPE("landscape.png"), LANGUAGE("language.png"), LAPTOP("laptop.png"),
    LAPTOP_CHROMEBOOK("laptop_chromebook.png"), LAPTOP_MAC("laptop_mac.png"), LAPTOP_WINDOWS("laptop_windows.png"),
    LAST_PAGE("last_page.png"), LAUNCH("launch.png"), LAYERS("layers.png"), LAYERS_CLEAR("layers_clear.png"),
    LEAK_ADD("leak_add.png"), LEAK_REMOVE("leak_remove.png"), LENS("lens.png"), LESS_THAN("less_than.png"),
    LESS_THAN_EQUAL("less_than_equal.png"), LIBRARY_ADD("library_add.png"), LIBRARY_BOOKS("library_books.png"),
    LIBRARY_MUSIC("library_music.png"), LIGHTBULB("lightbulb.png"), LINE_STYLE("line_style.png"),
    LINE_WEIGHT("line_weight.png"), LINEAR_SCALE("linear_scale.png"), LINK("link.png"), LINK_OFF("link_off.png"),
    LINKED_CAMERA("linked_camera.png"), LIST("list.png"), LIST_ALT("list_alt.png"), LIVE_HELP("live_help.png"),
    LIVE_TV("live_tv.png"), LOCAL_ACTIVITY("local_activity.png"), LOCAL_AIRPORT("local_airport.png"),
    LOCAL_ATM("local_atm.png"), LOCAL_BAR("local_bar.png"), LOCAL_CAFE("local_cafe.png"),
    LOCAL_CAR_WASH("local_car_wash.png"), LOCAL_CONVENIENCE_STORE("local_convenience_store.png"),
    LOCAL_DINING("local_dining.png"), LOCAL_DRINK("local_drink.png"), LOCAL_FLORIST("local_florist.png"),
    LOCAL_GAS_STATION("local_gas_station.png"), LOCAL_GROCERY_STORE("local_grocery_store.png"),
    LOCAL_HOSPITAL("local_hospital.png"), LOCAL_HOTEL("local_hotel.png"),
    LOCAL_LAUNDRY_SERVICE("local_laundry_service.png"), LOCAL_LIBRARY("local_library.png"),
    LOCAL_MALL("local_mall.png"), LOCAL_MOVIES("local_movies.png"), LOCAL_OFFER("local_offer.png"),
    LOCAL_PARKING("local_parking.png"), LOCAL_PHARMACY("local_pharmacy.png"), LOCAL_PHONE("local_phone.png"),
    LOCAL_PIZZA("local_pizza.png"), LOCAL_PLAY("local_play.png"), LOCAL_POST_OFFICE("local_post_office.png"),
    LOCAL_PRINTSHOP("local_printshop.png"), LOCAL_SEE("local_see.png"), LOCAL_SHIPPING("local_shipping.png"),
    LOCAL_TAXI("local_taxi.png"), LOCATION_CITY("location_city.png"), LOCATION_DISABLED("location_disabled.png"),
    LOCATION_OFF("location_off.png"), LOCATION_ON("location_on.png"), LOCATION_SEARCHING("location_searching.png"),
    LOCK("lock.png"), LOCK_OPEN("lock_open.png"), LOG_IN("log_in.png"), LOG_OUT("log_out.png"), LOOKS("looks.png"),
    LOOKS_3("looks_3.png"), LOOKS_4("looks_4.png"), LOOKS_5("looks_5.png"), LOOKS_6("looks_6.png"),
    LOOKS_ONE("looks_one.png"), LOOKS_TWO("looks_two.png"), LOOP("loop.png"), LOUPE("loupe.png"),
    LOW_PRIORITY("low_priority.png"), LOYALTY("loyalty.png"), MAIL("mail.png"), MAIL_OUTLINE("mail_outline.png"),
    MAP("map.png"), MARKUNREAD("markunread.png"), MARKUNREAD_MAILBOX("markunread_mailbox.png"),
    MAXIMIZE("maximize.png"), MEETING_ROOM("meeting_room.png"), MEMORY("memory.png"), MENU("menu.png"),
    MENU_BOOK("menu_book.png"), MENU_OPEN("menu_open.png"), MERGE_TYPE("merge_type.png"), MESSAGE("models.message.png"),
    MIC("mic.png"), MIC_NONE("mic_none.png"), MIC_OFF("mic_off.png"), MINIMIZE("minimize.png"), MINUS("minus.png"),
    MISSED_VIDEO_CALL("missed_video_call.png"), MMS("mms.png"), MOBILE_FRIENDLY("mobile_friendly.png"),
    MOBILE_OFF("mobile_off.png"), MOBILE_SCREEN_SHARE("mobile_screen_share.png"), MODE_COMMENT("mode_comment.png"),
    MONETIZATION_ON("monetization_on.png"), MONEY("money.png"), MONEY_OFF("money_off.png"),
    MONOCHROME_PHOTOS("monochrome_photos.png"), MOOD("mood.png"), MOOD_BAD("mood_bad.png"), MORE("more.png"),
    MORE_HORIZ("more_horiz.png"), MORE_VERT("more_vert.png"), MOTORCYCLE("motorcycle.png"), MOUSE("mouse.png"),
    MOVE_TO_INBOX("move_to_inbox.png"), MOVIE("movie.png"), MOVIE_CREATION("movie_creation.png"),
    MOVIE_FILTER("movie_filter.png"), MULTILINE_CHART("multiline_chart.png"), MUSEUM("museum.png"),
    MUSIC_NOTE("music_note.png"), MUSIC_OFF("music_off.png"), MUSIC_VIDEO("music_video.png"),
    MY_LOCATION("my_location.png"), NATURE("nature.png"), NATURE_PEOPLE("nature_people.png"),
    NAVIGATE_BEFORE("navigate_before.png"), NAVIGATE_NEXT("navigate_next.png"), NAVIGATION("navigation.png"),
    NEAR_ME("near_me.png"), NETWORK_CELL("network_cell.png"), NETWORK_CHECK("network_check.png"),
    NETWORK_LOCKED("network_locked.png"), NETWORK_WIFI("network_wifi.png"), NEW_RELEASES("new_releases.png"),
    NEXT_WEEK("next_week.png"), NFC("nfc.png"), NIGHTS_STAY("nights_stay.png"), NO_ENCRYPTION("no_encryption.png"),
    NO_MEETING_ROOM("no_meeting_room.png"), NO_SIM("no_sim.png"), NOT_EQUAL("not_equal.png"),
    NOT_INTERESTED("not_interested.png"), NOT_LISTED_LOCATION("not_listed_location.png"), NOTE("note.png"),
    NOTE_ADD("note_add.png"), NOTES("notes.png"), NOTIFICATION_IMPORTANT("notification_important.png"),
    NOTIFICATIONS("notifications.png"), NOTIFICATIONS_ACTIVE("notifications_active.png"),
    NOTIFICATIONS_NONE("notifications_none.png"), NOTIFICATIONS_OFF("notifications_off.png"),
    NOTIFICATIONS_PAUSED("notifications_paused.png"), OFFLINE_BOLT("offline_bolt.png"), OFFLINE_PIN("offline_pin.png"),
    ONDEMAND_VIDEO("ondemand_video.png"), OPACITY("opacity.png"), OPEN_IN_BROWSER("open_in_browser.png"),
    OPEN_IN_NEW("open_in_new.png"), OPEN_WITH("open_with.png"), OUTDOOR_GRILL("outdoor_grill.png"),
    OUTLINED_FLAG("outlined_flag.png"), PAGES("pages.png"), PAGEVIEW("pageview.png"), PALETTE("palette.png"),
    PAN_TOOL("pan_tool.png"), PANORAMA("panorama.png"), PANORAMA_FISH_EYE("panorama_fish_eye.png"),
    PANORAMA_HORIZONTAL("panorama_horizontal.png"), PANORAMA_VERTICAL("panorama_vertical.png"),
    PANORAMA_WIDE_ANGLE("panorama_wide_angle.png"), PARTY_MODE("party_mode.png"), PAUSE("pause.png"),
    PAUSE_CIRCLE_FILLED("pause_circle_filled.png"), PAUSE_CIRCLE_OUTLINE("pause_circle_outline.png"),
    PAUSE_PRESENTATION("pause_presentation.png"), PAYMENT("payment.png"), PEOPLE("people.png"),
    PEOPLE_ALT("people_alt.png"), PEOPLE_OUTLINE("people_outline.png"), PERCENTAGE("percentage.png"),
    PERM_CAMERA_MIC("perm_camera_mic.png"), PERM_CONTACT_CALENDAR("perm_contact_calendar.png"),
    PERM_DATA_SETTING("perm_data_setting.png"), PERM_DEVICE_INFORMATION("perm_device_information.png"),
    PERM_IDENTITY("perm_identity.png"), PERM_MEDIA("perm_media.png"), PERM_PHONE_MSG("perm_phone_msg.png"),
    PERM_SCAN_WIFI("perm_scan_wifi.png"), PERSON("person.png"), PERSON_ADD("person_add.png"),
    PERSON_ADD_DISABLED("person_add_disabled.png"), PERSON_OUTLINE("person_outline.png"), PERSON_PIN("person_pin.png"),
    PERSON_PIN_CIRCLE("person_pin_circle.png"), PERSONAL_VIDEO("personal_video.png"), PETS("pets.png"),
    PHONE("phone.png"), PHONE_ANDROID("phone_android.png"), PHONE_BLUETOOTH_SPEAKER("phone_bluetooth_speaker.png"),
    PHONE_CALLBACK("phone_callback.png"), PHONE_DISABLED("phone_disabled.png"), PHONE_ENABLED("phone_enabled.png"),
    PHONE_FORWARDED("phone_forwarded.png"), PHONE_IN_TALK("phone_in_talk.png"), PHONE_IPHONE("phone_iphone.png"),
    PHONE_LOCKED("phone_locked.png"), PHONE_MISSED("phone_missed.png"), PHONE_PAUSED("phone_paused.png"),
    PHONELINK("phonelink.png"), PHONELINK_ERASE("phonelink_erase.png"), PHONELINK_LOCK("phonelink_lock.png"),
    PHONELINK_OFF("phonelink_off.png"), PHONELINK_RING("phonelink_ring.png"), PHONELINK_SETUP("phonelink_setup.png"),
    PHOTO("photo.png"), PHOTO_ALBUM("photo_album.png"), PHOTO_CAMERA("photo_camera.png"),
    PHOTO_FILTER("photo_filter.png"), PHOTO_LIBRARY("photo_library.png"),
    PHOTO_SIZE_SELECT_ACTUAL("photo_size_select_actual.png"), PHOTO_SIZE_SELECT_LARGE("photo_size_select_large.png"),
    PHOTO_SIZE_SELECT_SMALL("photo_size_select_small.png"), PICTURE_AS_PDF("picture_as_pdf.png"),
    PICTURE_IN_PICTURE("picture_in_picture.png"), PICTURE_IN_PICTURE_ALT("picture_in_picture_alt.png"),
    PIE_CHART("pie_chart.png"), PIN("pin.png"), PIN_DROP("pin_drop.png"), PIN_OFF("pin_off.png"), PLACE("place.png"),
    PLAY_ARROW("play_arrow.png"), PLAY_CIRCLE_FILLED("play_circle_filled.png"),
    PLAY_CIRCLE_FILLED_WHITE("play_circle_filled_white.png"), PLAY_CIRCLE_OUTLINE("play_circle_outline.png"),
    PLAY_FOR_WORK("play_for_work.png"), PLAYLIST_ADD("playlist_add.png"), PLAYLIST_ADD_CHECK("playlist_add_check.png"),
    PLAYLIST_PLAY("playlist_play.png"), PLUS("plus.png"), PLUS_MINUS("plus_minus.png"),
    PLUS_MINUS_ALT("plus_minus_alt.png"), PLUS_ONE("plus_one.png"), POLICY("policy.png"), POLL("poll.png"),
    POLYMER("polymer.png"), POOL("pool.png"), PORTABLE_WIFI_OFF("portable_wifi_off.png"), PORTRAIT("portrait.png"),
    POST_ADD("post_add.png"), POWER("power.png"), POWER_INPUT("power_input.png"), POWER_OFF("power_off.png"),
    POWER_SETTINGS_NEW("power_settings_new.png"), PREGNANT_WOMAN("pregnant_woman.png"),
    PRESENT_TO_ALL("present_to_all.png"), PRINT("print.png"), PRINT_DISABLED("print_disabled.png"),
    PRIORITY_HIGH("priority_high.png"), PUBLIC("public.png"), PUBLISH("publish.png"), QRCODE("qrcode.png"),
    QUERY_BUILDER("query_builder.png"), QUESTION_ANSWER("question_answer.png"), QUEUE("queue.png"),
    QUEUE_MUSIC("queue_music.png"), QUEUE_PLAY_NEXT("queue_play_next.png"), RADIO("radio.png"),
    RADIO_BUTTON_CHECKED("radio_button_checked.png"), RADIO_BUTTON_UNCHECKED("radio_button_unchecked.png"),
    RATE_REVIEW("rate_review.png"), RECEIPT("receipt.png"), RECENT_ACTORS("recent_actors.png"),
    RECORD_VOICE_OVER("record_voice_over.png"), REDEEM("redeem.png"), REDO("redo.png"), REFRESH("refresh.png"),
    REMOVE("remove.png"), REMOVE_CIRCLE("remove_circle.png"), REMOVE_CIRCLE_OUTLINE("remove_circle_outline.png"),
    REMOVE_FROM_QUEUE("remove_from_queue.png"), REMOVE_RED_EYE("remove_red_eye.png"),
    REMOVE_SHOPPING_CART("remove_shopping_cart.png"), REORDER("reorder.png"), REPEAT("repeat.png"),
    REPEAT_ONE("repeat_one.png"), REPLAY("replay.png"), REPLAY_10("replay_10.png"), REPLAY_30("replay_30.png"),
    REPLAY_5("replay_5.png"), REPLY("reply.png"), REPLY_ALL("reply_all.png"), REPORT("report.png"),
    REPORT_OFF("report_off.png"), REPORT_PROBLEM("report_problem.png"), RESTAURANT("restaurant.png"),
    RESTAURANT_MENU("restaurant_menu.png"), RESTORE("restore.png"), RESTORE_FROM_TRASH("restore_from_trash.png"),
    RESTORE_PAGE("restore_page.png"), RING_VOLUME("ring_volume.png"), ROCKET("rocket.png"), ROOM("room.png"),
    ROOM_SERVICE("room_service.png"), ROTATE_90_DEGREES_CCW("rotate_90_degrees_ccw.png"),
    ROTATE_LEFT("rotate_left.png"), ROTATE_RIGHT("rotate_right.png"), ROUNDED_CORNER("rounded_corner.png"),
    ROUTER("router.png"), ROWING("rowing.png"), RSS_FEED("rss_feed.png"), RV_HOOKUP("rv_hookup.png"),
    SATELLITE("satellite.png"), SAVE("save.png"), SAVE_ALT("save_alt.png"), SCANNER("scanner.png"),
    SCATTER_PLOT("scatter_plot.png"), SCHEDULE("schedule.png"), SCHOOL("school.png"), SCORE("score.png"),
    SCREEN_LOCK_LANDSCAPE("screen_lock_landscape.png"), SCREEN_LOCK_PORTRAIT("screen_lock_portrait.png"),
    SCREEN_LOCK_ROTATION("screen_lock_rotation.png"), SCREEN_ROTATION("screen_rotation.png"),
    SCREEN_SHARE("screen_share.png"), SD_CARD("sd_card.png"), SD_STORAGE("sd_storage.png"), SEARCH("search.png"),
    SECURITY("security.png"), SELECT_ALL("select_all.png"), SEND("send.png"),
    SENTIMENT_DISSATISFIED("sentiment_dissatisfied.png"), SENTIMENT_NEUTRAL("sentiment_neutral.png"),
    SENTIMENT_SATISFIED("sentiment_satisfied.png"), SENTIMENT_SATISFIED_ALT("sentiment_satisfied_alt.png"),
    SENTIMENT_SLIGHTLY_DISSATISFIED("sentiment_slightly_dissatisfied.png"),
    SENTIMENT_VERY_DISSATISFIED("sentiment_very_dissatisfied.png"),
    SENTIMENT_VERY_SATISFIED("sentiment_very_satisfied.png"), SETTINGS("settings.png"),
    SETTINGS_APPLICATIONS("settings_applications.png"), SETTINGS_BACKUP_RESTORE("settings_backup_restore.png"),
    SETTINGS_BLUETOOTH("settings_bluetooth.png"), SETTINGS_BRIGHTNESS("settings_brightness.png"),
    SETTINGS_CELL("settings_cell.png"), SETTINGS_ETHERNET("settings_ethernet.png"),
    SETTINGS_INPUT_ANTENNA("settings_input_antenna.png"), SETTINGS_INPUT_COMPONENT("settings_input_component.png"),
    SETTINGS_INPUT_COMPOSITE("settings_input_composite.png"), SETTINGS_INPUT_HDMI("settings_input_hdmi.png"),
    SETTINGS_INPUT_SVIDEO("settings_input_svideo.png"), SETTINGS_OVERSCAN("settings_overscan.png"),
    SETTINGS_PHONE("settings_phone.png"), SETTINGS_POWER("settings_power.png"), SETTINGS_REMOTE("settings_remote.png"),
    SETTINGS_SYSTEM_DAYDREAM("settings_system_daydream.png"), SETTINGS_VOICE("settings_voice.png"), SHARE("share.png"),
    SHOP("shop.png"), SHOP_TWO("shop_two.png"), SHOPPING_BASKET("shopping_basket.png"),
    SHOPPING_CART("shopping_cart.png"), SHORT_TEXT("short_text.png"), SHOW_CHART("show_chart.png"),
    SHUFFLE("shuffle.png"), SHUTTER_SPEED("shutter_speed.png"), SIGNAL_CELLULAR_0_BAR("signal_cellular_0_bar.png"),
    SIGNAL_CELLULAR_1_BAR("signal_cellular_1_bar.png"), SIGNAL_CELLULAR_2_BAR("signal_cellular_2_bar.png"),
    SIGNAL_CELLULAR_3_BAR("signal_cellular_3_bar.png"), SIGNAL_CELLULAR_4_BAR("signal_cellular_4_bar.png"),
    SIGNAL_CELLULAR_ALT("signal_cellular_alt.png"),
    SIGNAL_CELLULAR_CONNECTED_NO_INTERNET_0_BAR("signal_cellular_connected_no_internet_0_bar.png"),
    SIGNAL_CELLULAR_CONNECTED_NO_INTERNET_1_BAR("signal_cellular_connected_no_internet_1_bar.png"),
    SIGNAL_CELLULAR_CONNECTED_NO_INTERNET_2_BAR("signal_cellular_connected_no_internet_2_bar.png"),
    SIGNAL_CELLULAR_CONNECTED_NO_INTERNET_3_BAR("signal_cellular_connected_no_internet_3_bar.png"),
    SIGNAL_CELLULAR_CONNECTED_NO_INTERNET_4_BAR("signal_cellular_connected_no_internet_4_bar.png"),
    SIGNAL_CELLULAR_NO_SIM("signal_cellular_no_sim.png"), SIGNAL_CELLULAR_NULL("signal_cellular_null.png"),
    SIGNAL_CELLULAR_OFF("signal_cellular_off.png"), SIGNAL_WIFI_0_BAR("signal_wifi_0_bar.png"),
    SIGNAL_WIFI_1_BAR("signal_wifi_1_bar.png"), SIGNAL_WIFI_1_BAR_LOCK("signal_wifi_1_bar_lock.png"),
    SIGNAL_WIFI_2_BAR("signal_wifi_2_bar.png"), SIGNAL_WIFI_2_BAR_LOCK("signal_wifi_2_bar_lock.png"),
    SIGNAL_WIFI_3_BAR("signal_wifi_3_bar.png"), SIGNAL_WIFI_3_BAR_LOCK("signal_wifi_3_bar_lock.png"),
    SIGNAL_WIFI_4_BAR("signal_wifi_4_bar.png"), SIGNAL_WIFI_4_BAR_LOCK("signal_wifi_4_bar_lock.png"),
    SIGNAL_WIFI_OFF("signal_wifi_off.png"), SIM_CARD("sim_card.png"), SIM_CARD_ALERT("sim_card_alert.png"),
    SINGLE_BED("single_bed.png"), SKIP_NEXT("skip_next.png"), SKIP_PREVIOUS("skip_previous.png"),
    SLIDESHOW("slideshow.png"), SLOW_MOTION_VIDEO("slow_motion_video.png"), SMARTPHONE("smartphone.png"),
    SMOKE_FREE("smoke_free.png"), SMOKING_ROOMS("smoking_rooms.png"), SMS("sms.png"), SMS_FAILED("sms_failed.png"),
    SNOOZE("snooze.png"), SORT("sort.png"), SORT_BY_ALPHA("sort_by_alpha.png"), SPA("spa.png"),
    SPACE_BAR("space_bar.png"), SPEAKER("speaker.png"), SPEAKER_GROUP("speaker_group.png"),
    SPEAKER_NOTES("speaker_notes.png"), SPEAKER_NOTES_OFF("speaker_notes_off.png"), SPEAKER_PHONE("speaker_phone.png"),
    SPEED("speed.png"), SPELLCHECK("spellcheck.png"), SPORTS("sports.png"), SPORTS_BASEBALL("sports_baseball.png"),
    SPORTS_BASKETBALL("sports_basketball.png"), SPORTS_CRICKET("sports_cricket.png"),
    SPORTS_ESPORTS("sports_esports.png"), SPORTS_FOOTBALL("sports_football.png"), SPORTS_GOLF("sports_golf.png"),
    SPORTS_HANDBALL("sports_handball.png"), SPORTS_HOCKEY("sports_hockey.png"), SPORTS_KABADDI("sports_kabaddi.png"),
    SPORTS_MMA("sports_mma.png"), SPORTS_MOTORSPORTS("sports_motorsports.png"), SPORTS_RUGBY("sports_rugby.png"),
    SPORTS_SOCCER("sports_soccer.png"), SPORTS_TENNIS("sports_tennis.png"), SPORTS_VOLLEYBALL("sports_volleyball.png"),
    SQUARE_FOOT("square_foot.png"), STAR("star.png"), STAR_BORDER("star_border.png"), STAR_HALF("star_half.png"),
    STAR_RATE("star_rate.png"), STARS("stars.png"), STAY_CURRENT_LANDSCAPE("stay_current_landscape.png"),
    STAY_CURRENT_PORTRAIT("stay_current_portrait.png"), STAY_PRIMARY_LANDSCAPE("stay_primary_landscape.png"),
    STAY_PRIMARY_PORTRAIT("stay_primary_portrait.png"), STOP("stop.png"), STOP_CIRCLE("stop_circle.png"),
    STOP_SCREEN_SHARE("stop_screen_share.png"), STORAGE("storage.png"), STORE("store.png"),
    STORE_MALL_DIRECTORY("store_mall_directory.png"), STOREFRONT("storefront.png"), STRAIGHTEN("straighten.png"),
    STREETVIEW("streetview.png"), STRIKETHROUGH_S("strikethrough_s.png"), STYLE("style.png"),
    SUBDIRECTORY_ARROW_LEFT("subdirectory_arrow_left.png"), SUBDIRECTORY_ARROW_RIGHT("subdirectory_arrow_right.png"),
    SUBJECT("subject.png"), SUBSCRIPTIONS("subscriptions.png"), SUBTITLES("subtitles.png"), SUBWAY("subway.png"),
    SUPERVISED_USER_CIRCLE("supervised_user_circle.png"), SUPERVISOR_ACCOUNT("supervisor_account.png"),
    SURROUND_SOUND("surround_sound.png"), SWAP_CALLS("swap_calls.png"), SWAP_HORIZ("swap_horiz.png"),
    SWAP_HORIZONTAL_CIRCLE("swap_horizontal_circle.png"), SWAP_VERT("swap_vert.png"),
    SWAP_VERTICAL_CIRCLE("swap_vertical_circle.png"), SWITCH_CAMERA("switch_camera.png"),
    SWITCH_VIDEO("switch_video.png"), SYNC("sync.png"), SYNC_ALT("sync_alt.png"), SYNC_DISABLED("sync_disabled.png"),
    SYNC_PROBLEM("sync_problem.png"), SYSTEM_UPDATE("system_update.png"), SYSTEM_UPDATE_ALT("system_update_alt.png"),
    TAB("tab.png"), TAB_UNSELECTED("tab_unselected.png"), TABLE_CHART("table_chart.png"), TABLET("tablet.png"),
    TABLET_ANDROID("tablet_android.png"), TABLET_MAC("tablet_mac.png"), TAG_FACES("tag_faces.png"),
    TAP_AND_PLAY("tap_and_play.png"), TERRAIN("terrain.png"), TEXT_FIELDS("text_fields.png"),
    TEXT_FORMAT("text_format.png"), TEXT_ROTATE_UP("text_rotate_up.png"),
    TEXT_ROTATE_VERTICAL("text_rotate_vertical.png"), TEXT_ROTATION_ANGLEDOWN("text_rotation_angledown.png"),
    TEXT_ROTATION_ANGLEUP("text_rotation_angleup.png"), TEXT_ROTATION_DOWN("text_rotation_down.png"),
    TEXT_ROTATION_NONE("text_rotation_none.png"), TEXTSMS("textsms.png"), TEXTURE("texture.png"),
    THEATERS("theaters.png"), THUMB_DOWN("thumb_down.png"), THUMB_DOWN_ALT("thumb_down_alt.png"),
    THUMB_UP("thumb_up.png"), THUMB_UP_ALT("thumb_up_alt.png"), THUMBS_UP_DOWN("thumbs_up_down.png"),
    TIME_TO_LEAVE("time_to_leave.png"), TIMELAPSE("timelapse.png"), TIMELINE("timeline.png"), TIMER("timer.png"),
    TIMER_10("timer_10.png"), TIMER_3("timer_3.png"), TIMER_OFF("timer_off.png"), TITLE("title.png"), TOC("toc.png"),
    TODAY("today.png"), TOGGLE_OFF("toggle_off.png"), TOGGLE_ON("toggle_on.png"), TOLL("toll.png"),
    TONALITY("tonality.png"), TOUCH_APP("touch_app.png"), TOYS("toys.png"), TRACK_CHANGES("track_changes.png"),
    TRAFFIC("traffic.png"), TRAIN("train.png"), TRAM("tram.png"),
    TRANSFER_WITHIN_A_STATION("transfer_within_a_station.png"), TRANSFORM("transform.png"),
    TRANSIT_ENTEREXIT("transit_enterexit.png"), TRANSLATE("translate.png"), TRENDING_DOWN("trending_down.png"),
    TRENDING_FLAT("trending_flat.png"), TRENDING_UP("trending_up.png"), TRIP_ORIGIN("trip_origin.png"),
    TUNE("tune.png"), TURNED_IN("turned_in.png"), TURNED_IN_NOT("turned_in_not.png"), TV("tv.png"),
    TV_OFF("tv_off.png"), UNARCHIVE("unarchive.png"), UNDO("undo.png"), UNFOLD_LESS("unfold_less.png"),
    UNFOLD_MORE("unfold_more.png"), UNSUBSCRIBE("unsubscribe.png"), UPDATE("update.png"), USB("usb.png"),
    VERIFIED_USER("verified_user.png"), VERTICAL_ALIGN_BOTTOM("vertical_align_bottom.png"),
    VERTICAL_ALIGN_CENTER("vertical_align_center.png"), VERTICAL_ALIGN_TOP("vertical_align_top.png"),
    VERTICAL_SPLIT("vertical_split.png"), VIBRATION("vibration.png"), VIDEO_CALL("video_call.png"),
    VIDEO_LABEL("video_label.png"), VIDEO_LIBRARY("video_library.png"), VIDEOCAM("videocam.png"),
    VIDEOCAM_OFF("videocam_off.png"), VIDEOGAME_ASSET("videogame_asset.png"), VIEW_AGENDA("view_agenda.png"),
    VIEW_ARRAY("view_array.png"), VIEW_CAROUSEL("view_carousel.png"), VIEW_COLUMN("view_column.png"),
    VIEW_COMFY("view_comfy.png"), VIEW_COMPACT("view_compact.png"), VIEW_DAY("view_day.png"),
    VIEW_HEADLINE("view_headline.png"), VIEW_LIST("view_list.png"), VIEW_MODULE("view_module.png"),
    VIEW_QUILT("view_quilt.png"), VIEW_STREAM("view_stream.png"), VIEW_WEEK("view_week.png"), VIGNETTE("vignette.png"),
    VISIBILITY("visibility.png"), VISIBILITY_OFF("visibility_off.png"), VOICE_CHAT("voice_chat.png"),
    VOICE_OVER_OFF("voice_over_off.png"), VOICEMAIL("voicemail.png"), VOLUME_DOWN("volume_down.png"),
    VOLUME_MUTE("volume_mute.png"), VOLUME_OFF("volume_off.png"), VOLUME_UP("volume_up.png"), VPN_KEY("vpn_key.png"),
    VPN_LOCK("vpn_lock.png"), WALLPAPER("wallpaper.png"), WARNING("warning.png"), WATCH("watch.png"),
    WATCH_LATER("watch_later.png"), WAVES("waves.png"), WB_AUTO("wb_auto.png"), WB_CLOUDY("wb_cloudy.png"),
    WB_INCANDESCENT("wb_incandescent.png"), WB_IRIDESCENT("wb_iridescent.png"), WB_SUNNY("wb_sunny.png"), WC("wc.png"),
    WEB("web.png"), WEB_ASSET("web_asset.png"), WEEKEND("weekend.png"), WHATSHOT("whatshot.png"),
    WHERE_TO_VOTE("where_to_vote.png"), WIDGETS("views.widgets.png"), WIFI("wifi.png"), WIFI_LOCK("wifi_lock.png"),
    WIFI_OFF("wifi_off.png"), WIFI_TETHERING("wifi_tethering.png"), WORK("work.png"), WORK_OFF("work_off.png"),
    WORK_OUTLINE("work_outline.png"), WRAP_TEXT("wrap_text.png"), YOUTUBE_SEARCHED_FOR("youtube_searched_for.png"),
    ZOOM_IN("zoom_in.png"), ZOOM_OUT("zoom_out.png"), ZOOM_OUT_MAP("zoom_out_map.png");

    public final String path;

    Icon(String path) {
        this.path = "assets/icons/" + path;
    }
}